#!/usr/bin/env node

/**
 * Installs FlowDev-AI Pre-Commit Hook into .git/hooks/pre-commit.
 */

const fs = require("fs");
const path = require("path");
const { execSync } = require("child_process");

const rootDir = path.resolve(__dirname, "..");
const gitDir = path.join(rootDir, ".git");
const hooksDir = path.join(gitDir, "hooks");
const hookPath = path.join(hooksDir, "pre-commit");

console.log("\n📦 正在安装 FlowDev-AI Git Pre-Commit 代码审查门禁钩子...");

// 1. Check if git repo exists, if not initialize it
if (!fs.existsSync(gitDir)) {
  console.log("ℹ️  未检测到 .git 仓库，正在初始化 git 仓库 (git init)...");
  try {
    execSync("git init", { cwd: rootDir, stdio: "inherit" });
  } catch (e) {
    console.error("❌ 初始化 git 仓库失败:", e.message);
    process.exit(1);
  }
}

// 2. Ensure .git/hooks directory exists
if (!fs.existsSync(hooksDir)) {
  fs.mkdirSync(hooksDir, { recursive: true });
}

// 3. Script content for pre-commit hook (cross-platform for Windows Git Bash, macOS, Linux)
const hookScript = `#!/bin/sh
# FlowDev-AI Pre-Commit Hook
# Auto-generated by FlowDev-AI install-hook script

node scripts/flowdev-hook.js
`;

try {
  fs.writeFileSync(hookPath, hookScript, { encoding: "utf-8", mode: 0o755 });
  // Try chmod if supported on platform
  try {
    fs.chmodSync(hookPath, 0o755);
  } catch (e) {
    // Windows might ignore chmodSync, which is normal
  }

  console.log("✔ 钩子脚本安装成功！");
  console.log(`   目标路径: ${hookPath}`);
  console.log("   触发方式: 执行 'git commit' 时将自动触发 FlowDev AI 门禁扫描。\n");
} catch (err) {
  console.error("❌ 写入 pre-commit 钩子失败:", err.message);
  process.exit(1);
}
